# for details on settings, see https://docs.rendercv.com/user_guide/yaml_input_structure/settings/
rendercv_settings:
  render_command:
    dont_generate_markdown: true
    dont_generate_html: true
    dont_generate_pdf: false
    dont_generate_png: true
  bold_keywords: []
